alertmanager:
  enabled: false

grafana:
  adminUser: admin
  adminPassword: admin123
  service:
    type: NodePort
    nodePort: 30300

prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 3Gi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  admissionWebhooks:
    enabled: false