apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-devops
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-devops
  template:
    metadata:
      labels:
        app: app-devops
    spec:
      containers:
        - name: app-devops
          image: mlopeesz/app-devops:v1
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10