apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-app
  namespace: faculdade
spec:
  replicas: 4
  selector:
    matchLabels:
      app: minha-app
  template:
    metadata:
      labels:
        app: minha-app
    spec:
      containers:
      - name: minha-app
        image: mlopeesz/app-trabalho-pos:v1
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3