pipeline {
    agent {
        docker {
            image 'node:18'
        }
    }

    stages {
        stage('Run App') {
            steps {
                sh 'npm install'
            }
        }
    }
}